export const nativeNames: Record<string, string> = {
  "Afghanistan": "افغانستان",
  "Albania": "Shqipëria",
  "Algeria": "الجزائر",
  "Andorra": "Andorra",
  "Angola": "Angola",
  "Antarctica": "Antarctica",
  "Argentina": "Argentina",
  "Armenia": "Հայաստան",
  "Australia": "Australia",
  "Austria": "Österreich",
  "Azerbaijan": "Azərbaycan",
  "Bahamas": "Bahamas",
  "Bahrain": "البحرين",
  "Bangladesh": "বাংলাদেশ",
  "Barbados": "Barbados",
  "Belarus": "Беларусь",
  "Belgium": "België",
  "Belize": "Belize",
  "Benin": "Bénin",
  "Bhutan": "འབྲུག་ཡུལ་",
  "Bolivia": "Bolivia",
  "Bosnia and Herz.": "Bosna i Hercegovina",
  "Botswana": "Botswana",
  "Brazil": "Brasil",
  "Brunei": "Brunei",
  "Bulgaria": "България",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cambodia": "កម្ពុជា",
  "Cameroon": "Cameroun",
  "Canada": "Canada",
  "Cape Verde": "Cabo Verde",
  "Central African Rep.": "République centrafricaine",
  "Chad": "Tchad",
  "Chile": "Chile",
  "China": "中国",
  "Colombia": "Colombia",
  "Comoros": "Comores",
  "Congo": "Congo",
  "Dem. Rep. Congo": "République démocratique du Congo",
  "Costa Rica": "Costa Rica",
  "Croatia": "Hrvatska",
  "Cuba": "Cuba",
  "Cyprus": "Κύπρος",
  "Czech Rep.": "Česko",
  "Denmark": "Danmark",
  "Djibouti": "Djibouti",
  "Dominica": "Dominica",
  "Dominican Rep.": "República Dominicana",
  "Ecuador": "Ecuador",
  "Egypt": "مصر",
  "El Salvador": "El Salvador",
  "Equatorial Guinea": "Guinea Ecuatorial",
  "Eritrea": "Eritrea",
  "Estonia": "Eesti",
  "Ethiopia": "ኢትዮጵያ",
  "Fiji": "Fiji",
  "Finland": "Suomi",
  "France": "France",
  "Gabon": "Gabon",
  "Gambia": "Gambia",
  "Georgia": "საქართველო",
  "Germany": "Deutschland",
  "Ghana": "Ghana",
  "Greece": "Ελλάδα",
  "Grenada": "Grenada",
  "Guatemala": "Guatemala",
  "Guinea": "Guinée",
  "Guinea-Bissau": "Guiné-Bissau",
  "Guyana": "Guyana",
  "Haiti": "Haïti",
  "Honduras": "Honduras",
  "Hungary": "Magyarország",
  "Iceland": "Ísland",
  "India": "भारत",
  "Indonesia": "Indonesia",
  "Iran": "ایران",
  "Iraq": "العراق",
  "Ireland": "Éire",
  "Israel": "ישראל",
  "Italy": "Italia",
  "Jamaica": "Jamaica",
  "Japan": "日本",
  "Jordan": "الأردن",
  "Kazakhstan": "Қазақстан",
  "Kenya": "Kenya",
  "Kiribati": "Kiribati",
  "Korea": "대한민국",
  "Dem. Rep. Korea": "조선민주주의인민공화국",
  "Kuwait": "الكويت",
  "Kyrgyzstan": "Кыргызстан",
  "Laos": "ລາວ",
  "Latvia": "Latvija",
  "Lebanon": "لبنان",
  "Lesotho": "Lesotho",
  "Liberia": "Liberia",
  "Libya": "ليبيا",
  "Liechtenstein": "Liechtenstein",
  "Lithuania": "Lietuva",
  "Luxembourg": "Luxembourg",
  "Macedonia": "Македонија",
  "Madagascar": "Madagasikara",
  "Malawi": "Malawi",
  "Malaysia": "Malaysia",
  "Maldives": "Maldives",
  "Mali": "Mali",
  "Malta": "Malta",
  "Marshall Islands": "Marshall Islands",
  "Mauritania": "موريتانيا",
  "Mauritius": "Maurice",
  "Mexico": "México",
  "Micronesia": "Micronesia",
  "Moldova": "Moldova",
  "Monaco": "Monaco",
  "Mongolia": "Монгол улс",
  "Montenegro": "Crna Gora",
  "Morocco": "المغرب",
  "Mozambique": "Moçambique",
  "Myanmar": "မြန်မာ",
  "Namibia": "Namibia",
  "Nauru": "Nauru",
  "Nepal": "नेपाल",
  "Netherlands": "Nederland",
  "New Zealand": "New Zealand",
  "Nicaragua": "Nicaragua",
  "Niger": "Niger",
  "Nigeria": "Nigeria",
  "Norway": "Norge",
  "Oman": "عمان",
  "Pakistan": "پاکستان",
  "Palau": "Palau",
  "Panama": "Panamá",
  "Papua New Guinea": "Papua New Guinea",
  "Paraguay": "Paraguay",
  "Peru": "Perú",
  "Philippines": "Pilipinas",
  "Poland": "Polska",
  "Portugal": "Portugal",
  "Qatar": "قطر",
  "Romania": "România",
  "Russia": "Россия",
  "Rwanda": "Rwanda",
  "Saint Kitts and Nevis": "Saint Kitts and Nevis",
  "Saint Lucia": "Saint Lucia",
  "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
  "Samoa": "Samoa",
  "San Marino": "San Marino",
  "Sao Tome and Principe": "São Tomé e Príncipe",
  "Saudi Arabia": "المملكة العربية السعودية",
  "Senegal": "Sénégal",
  "Serbia": "Србија",
  "Seychelles": "Seychelles",
  "Sierra Leone": "Sierra Leone",
  "Singapore": "Singapore",
  "Slovakia": "Slovensko",
  "Slovenia": "Slovenija",
  "Solomon Islands": "Solomon Islands",
  "Somalia": "Soomaaliya",
  "South Africa": "South Africa",
  "South Sudan": "South Sudan",
  "Spain": "España",
  "Sri Lanka": "ශ්‍රී ලංකාව",
  "Sudan": "السودان",
  "Suriname": "Suriname",
  "Swaziland": "Swaziland",
  "Sweden": "Sverige",
  "Switzerland": "Schweiz",
  "Syria": "سوريا",
  "Taiwan": "台灣",
  "Tajikistan": "Тоҷикистон",
  "Tanzania": "Tanzania",
  "Thailand": "ประเทศไทย",
  "Timor-Leste": "Timor-Leste",
  "Togo": "Togo",
  "Tonga": "Tonga",
  "Trinidad and Tobago": "Trinidad and Tobago",
  "Tunisia": "تونس",
  "Turkey": "Türkiye",
  "Turkmenistan": "Türkmenistan",
  "Tuvalu": "Tuvalu",
  "Uganda": "Uganda",
  "Ukraine": "Україна",
  "United Arab Emirates": "الإمارات العربية المتحدة",
  "United Kingdom": "United Kingdom",
  "United States": "United States",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Oʻzbekiston",
  "Vanuatu": "Vanuatu",
  "Vatican City": "Stato della Città del Vaticano",
  "Venezuela": "Venezuela",
  "Vietnam": "Việt Nam",
  "Yemen": "اليمن",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabwe"
};
