/**
 * GeoJSON 국가명 → ISO 3166-1 alpha-2 소문자 코드 매핑
 * flagcdn.com 기준: https://flagcdn.com/w160/{code}.png
 */
export const countryToCode: Record<string, string> = {
  // 아시아
  "Afghanistan": "af",
  "Armenia": "am",
  "Azerbaijan": "az",
  "Bahrain": "bh",
  "Bangladesh": "bd",
  "Bhutan": "bt",
  "Brunei": "bn",
  "Cambodia": "kh",
  "China": "cn",
  "Cyprus": "cy",
  "Georgia": "ge",
  "India": "in",
  "Indonesia": "id",
  "Iran": "ir",
  "Iraq": "iq",
  "Israel": "il",
  "Japan": "jp",
  "Jordan": "jo",
  "Kazakhstan": "kz",
  "Korea": "kr",
  "South Korea": "kr",
  "North Korea": "kp",
  "Kuwait": "kw",
  "Kyrgyzstan": "kg",
  "Laos": "la",
  "Lebanon": "lb",
  "Malaysia": "my",
  "Maldives": "mv",
  "Mongolia": "mn",
  "Myanmar": "mm",
  "Nepal": "np",
  "Oman": "om",
  "Pakistan": "pk",
  "Palestine": "ps",
  "Philippines": "ph",
  "Qatar": "qa",
  "Saudi Arabia": "sa",
  "Singapore": "sg",
  "Sri Lanka": "lk",
  "Syria": "sy",
  "Taiwan": "tw",
  "Tajikistan": "tj",
  "Thailand": "th",
  "Timor-Leste": "tl",
  "Turkey": "tr",
  "Turkmenistan": "tm",
  "United Arab Emirates": "ae",
  "Uzbekistan": "uz",
  "Vietnam": "vn",
  "Yemen": "ye",

  // 유럽
  "Albania": "al",
  "Andorra": "ad",
  "Austria": "at",
  "Belarus": "by",
  "Belgium": "be",
  "Bosnia and Herzegovina": "ba",
  "Bulgaria": "bg",
  "Croatia": "hr",
  "Czech Republic": "cz",
  "Czechia": "cz",
  "Denmark": "dk",
  "Estonia": "ee",
  "Finland": "fi",
  "France": "fr",
  "Germany": "de",
  "Greece": "gr",
  "Hungary": "hu",
  "Iceland": "is",
  "Ireland": "ie",
  "Italy": "it",
  "Kosovo": "xk",
  "Latvia": "lv",
  "Liechtenstein": "li",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Malta": "mt",
  "Moldova": "md",
  "Monaco": "mc",
  "Montenegro": "me",
  "Netherlands": "nl",
  "North Macedonia": "mk",
  "Norway": "no",
  "Poland": "pl",
  "Portugal": "pt",
  "Romania": "ro",
  "Russia": "ru",
  "San Marino": "sm",
  "Serbia": "rs",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Spain": "es",
  "Sweden": "se",
  "Switzerland": "ch",
  "Ukraine": "ua",
  "United Kingdom": "gb",
  "Vatican": "va",

  // 아메리카
  "Antigua and Barbuda": "ag",
  "Argentina": "ar",
  "Bahamas": "bs",
  "Barbados": "bb",
  "Belize": "bz",
  "Bolivia": "bo",
  "Brazil": "br",
  "Canada": "ca",
  "Chile": "cl",
  "Colombia": "co",
  "Costa Rica": "cr",
  "Cuba": "cu",
  "Dominica": "dm",
  "Dominican Republic": "do",
  "Ecuador": "ec",
  "El Salvador": "sv",
  "Grenada": "gd",
  "Guatemala": "gt",
  "Guyana": "gy",
  "Haiti": "ht",
  "Honduras": "hn",
  "Jamaica": "jm",
  "Mexico": "mx",
  "Nicaragua": "ni",
  "Panama": "pa",
  "Paraguay": "py",
  "Peru": "pe",
  "Saint Kitts and Nevis": "kn",
  "Saint Lucia": "lc",
  "Saint Vincent and the Grenadines": "vc",
  "Suriname": "sr",
  "Trinidad and Tobago": "tt",
  "United States of America": "us",
  "Uruguay": "uy",
  "Venezuela": "ve",

  // 아프리카
  "Algeria": "dz",
  "Angola": "ao",
  "Benin": "bj",
  "Botswana": "bw",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cameroon": "cm",
  "Cape Verde": "cv",
  "Central African Republic": "cf",
  "Chad": "td",
  "Comoros": "km",
  "Congo": "cg",
  "Democratic Republic of the Congo": "cd",
  "Djibouti": "dj",
  "Egypt": "eg",
  "Equatorial Guinea": "gq",
  "Eritrea": "er",
  "Eswatini": "sz",
  "Ethiopia": "et",
  "Gabon": "ga",
  "Gambia": "gm",
  "Ghana": "gh",
  "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Ivory Coast": "ci",
  "Kenya": "ke",
  "Lesotho": "ls",
  "Liberia": "lr",
  "Libya": "ly",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Mali": "ml",
  "Mauritania": "mr",
  "Mauritius": "mu",
  "Morocco": "ma",
  "Mozambique": "mz",
  "Namibia": "na",
  "Niger": "ne",
  "Nigeria": "ng",
  "Rwanda": "rw",
  "São Tomé and Príncipe": "st",
  "Senegal": "sn",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Somalia": "so",
  "South Africa": "za",
  "South Sudan": "ss",
  "Sudan": "sd",
  "Tanzania": "tz",
  "Togo": "tg",
  "Tunisia": "tn",
  "Uganda": "ug",
  "Zambia": "zm",
  "Zimbabwe": "zw",

  // 오세아니아
  "Australia": "au",
  "Fiji": "fj",
  "Kiribati": "ki",
  "Marshall Islands": "mh",
  "Micronesia": "fm",
  "Nauru": "nr",
  "New Zealand": "nz",
  "Palau": "pw",
  "Papua New Guinea": "pg",
  "Samoa": "ws",
  "Solomon Islands": "sb",
  "Tonga": "to",
  "Tuvalu": "tv",
  "Vanuatu": "vu",

  // 추가 매핑 (GeoJSON 변형 국가명 대비)
  "United States": "us",
  "U.S.A.": "us",
  "USA": "us",
  "Côte d'Ivoire": "ci",
  "Cabo Verde": "cv",
  "Lao PDR": "la",
  "Dem. Rep. Congo": "cd",
  "Central African Rep.": "cf",
  "S. Sudan": "ss",
  "W. Sahara": "eh",
  "Western Sahara": "eh",
  "Dominican Rep.": "do",
  "Bosnia and Herz.": "ba",
  "Macedonia": "mk",
  "Czech Rep.": "cz",
  "Eq. Guinea": "gq",
  "Solomon Is.": "sb",
  "East Timor": "tl",
  "England": "gb",
  "Falkland Islands": "fk",
  "Guinea Bissau": "gw",
  "Greenland": "gl",
  "New Caledonia": "nc",
  "Northern Cyprus": "cy",
  "Puerto Rico": "pr",
  "Republic of Serbia": "rs",
  "Republic of the Congo": "cg",
  "Somaliland": "so",
  "Swaziland": "sz",
  "The Bahamas": "bs",
  "United Republic of Tanzania": "tz",
  "West Bank": "ps",
  "Antarctica": "aq",
  "French Southern and Antarctic Lands": "tf",
};

/**
 * 국가명으로 flagcdn.com 이미지 URL을 반환.
 * 매핑이 없으면 null 반환 (fallback 처리는 호출자가 담당).
 */
export function getFlagUrl(countryName: string): string | null {
  const code = countryToCode[countryName];
  return code ? `https://flagcdn.com/w160/${code}.png` : null;
}
